solana_rpc_url = "https://api.devnet.solana.com"
solana_ws_url = "wss://api.devnet.solana.com/"
api_bind_address = "127.0.0.1"
port="8000"
database_url = "postgres://user:password@localhost/solana_db"  # Optional
transaction_signature = "55uZGP5pois5dA1PGtjA2Pq1H6z8Fhv8j8Z9e8k5yi5ZadvCCEDyCrSwmwKXGB83aLR5Qv7RJQdWfXBFrck8ZDHg"
account_pubkey = "Dn2A6nMEuyE5WFjf9n8M3nACVsbjKEhiXeff6CiD6mtx"
